version: "3.9"

services:
  angular:
    build: ./angular
    container_name: angular-builder
    volumes:
      - dist-folder:/app/dist
    command: tail -f /dev/null

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - dist-folder:/usr/share/nginx/html/app-angular
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist-folder:
  